### PR TITLE
Fix text in discord

### PR DESCRIPTION
**Pull request by AquUpd**
Everything was working good, but not chat
изображение
Fixed it

### CODE REVIEW

**Comment by HeyBanditoz** [comment]
@AquUpd 
Hmm, doesn't seem to work for me. I get this stacktrace:
```
[22:50:53] [Interweave/INFO] (Minecraft) [STDERR]: java.lang.ClassCastException: class java.lang.String cannot be cast to class net.minecraft.text.LiteralText (java.lang.String is in module java.base of loader 'bootstrap'; net.minecraft.text.LiteralText is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @662706a7)
[22:50:53] [Interweave/INFO] (Minecraft) [STDERR]: 	at main.Interweave.lambda$sendMessage$4(Interweave.java:165)
[22:50:53] [Interweave/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[22:50:53] [Interweave/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[22:50:53] [Interweave/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```
I noticed you seem to be speaking Russian, my friend and I speak English so perhaps that's it?

**Comment by AquUpd** [comment]
Hmmm, weird. Maybe I got this because i have plugins that changes how text appears?

**Comment by AquUpd** [comment]
https://www.curseforge.com/minecraft/mc-mods/chat/files This mod

**Comment by AquUpd** [comment]
I'll close it then

**Pull request closed without merging**
